#ifndef FEATURE_SDDS_MULTICAST_ENABLED
#define FEATURE_SDDS_MULTICAST_ENABLED
#endif
#ifndef FEATURE_SDDS_BUILTIN_TOPICS_ENABLED
#define FEATURE_SDDS_BUILTIN_TOPICS_ENABLED
#endif
#ifndef FEATURE_SDDS_DISCOVERY_ENABLED
#define FEATURE_SDDS_DISCOVERY_ENABLED
#endif
#ifndef SDDS_NET_MAX_BUF_SIZE
#define SDDS_NET_MAX_BUF_SIZE 1024
#endif
#ifndef SDDS_NET_MAX_LOCATOR_COUNT
#define SDDS_NET_MAX_LOCATOR_COUNT 20
#endif
#ifndef SDDS_DISCOVERY_RECEIVE_TIMER
#define SDDS_DISCOVERY_RECEIVE_TIMER 1
#endif
#ifndef SDDS_DISCOVERY_PARTICIPANT_TIMER
#define SDDS_DISCOVERY_PARTICIPANT_TIMER 1
#endif
#ifndef SDDS_DISCOVERY_PUBLICATION_TIMER
#define SDDS_DISCOVERY_PUBLICATION_TIMER 5
#endif
#ifndef SDDS_DISCOVERY_TOPIC_TIMER
#define SDDS_DISCOVERY_TOPIC_TIMER 0
#endif
#ifndef SDDS_QOS_LATENCYBUDGET
#define SDDS_QOS_LATENCYBUDGET
#endif
#ifndef SDDS_QOS_DW_LATBUD
#define SDDS_QOS_DW_LATBUD 5000
#endif
#ifndef SDDS_QOS_DW_COMM
#define SDDS_QOS_DW_COMM 1000
#endif
#ifndef SDDS_QOS_DW_READ
#define SDDS_QOS_DW_READ 1000
#endif
