Contiki 2.5: core/net/neighbor-info.h File Reference
neighbor-info.h File Reference
Declarations for the neighbor information module.
#include "net/neighbor-attr.h"
#include "net/rime.h"
Functions
void neighbor_info_packet_sent (int status, int numtx)
Notify the neighbor information module about the status of a packet transmission.
void neighbor_info_packet_received (void)
Notify the neighbor information module that a packet was received.
int neighbor_info_subscribe (neighbor_info_subscriber_t)
Subscribe to notifications of changed neighbor information.
link_metric_t neighbor_info_get_metric (const rimeaddr_t *addr)
Get link metric value for a specific neighbor.
Detailed Description
Declarations for the neighbor information module.
Author:
Nicolas Tsiftes <nvt@sics.se>
Definition in file neighbor-info.h.
Function Documentation
link_metric_t neighbor_info_get_metric (const rimeaddr_t * addr)
Get link metric value for a specific neighbor.
Returns:
Returns link metric if the neighbor exists, and 0 if not.
Definition at line 185 of file neighbor-info.c.
References NULL.
void neighbor_info_packet_received (void)
Notify the neighbor information module that a packet was received.
Parameters:
status The MAC status code for this packet.
numtx The amount of transmissions made for this packet.
Definition at line 156 of file neighbor-info.c.
References rimeaddr_cmp(), and rimeaddr_null.
void neighbor_info_packet_sent (int status, int numtx)
Notify the neighbor information module about the status of a packet transmission.
Parameters:
status The MAC status code for this packet.
numtx The amount of transmissions made for this packet.
Definition at line 109 of file neighbor-info.c.
References MAC_TX_NOACK, MAC_TX_OK, NULL, rimeaddr_cmp(), rimeaddr_null, and stimer_set().
int neighbor_info_subscribe (neighbor_info_subscriber_t)
Subscribe to notifications of changed neighbor information.
Returns:
Returns 1 if the subscription was successful, and 0 if not.
Definition at line 172 of file neighbor-info.c.
References NULL.