Contiki 2.5: cpu/stm32w108/board-sensors.h File Reference
board-sensors.h File Reference
Declarations for sensor-related functions that are common to all stm32w platforms.
Functions
void sensorsPowerDown ()
Remember state of sensors (if active or not), in order to resume their original state after calling powerUpSensors().
void sensorsPowerUp ()
Resume the state of all on-board sensors on to the state that they had when sensorsPowerDown() was called.
Detailed Description
Declarations for sensor-related functions that are common to all stm32w platforms.
Author:
Salvatore Pitrulli <salvopitru@users.sourceforge.net>
Definition in file board-sensors.h.
Function Documentation
void sensorsPowerDown ()
Remember state of sensors (if active or not), in order to resume their original state after calling powerUpSensors().
Useful when entering in sleep mode, since all system peripherals have to be reinitialized.
Definition at line 61 of file board-mb851.c.
References sensorsPowerDown(), and temperature_sensor.
Referenced by sensorsPowerDown().
void sensorsPowerUp ()
Resume the state of all on-board sensors on to the state that they had when sensorsPowerDown() was called.
Useful when sensors have to be used after the micro was put in deep sleep mode.
Definition at line 79 of file board-mb851.c.
References sensorsPowerUp(), and temperature_sensor.
Referenced by sensorsPowerUp().