Contiki 2.5: TR1001 radio tranciever device driver
TR1001 radio tranciever device driver
[The ESB Embedded Sensor Board]
Files
file tr1001-gcr.c
Device driver and packet framing for the RFM-TR1001 radio module.
file tr1001.c
Device driver and packet framing for the RFM-TR1001 radio module.
Functions
void tr1001_set_txpower (unsigned char p)
Set the transmission power of the transceiver.
int tr1001_init (void)
Initialize the radio transceiver.
Variables
struct radio_driver tr1001_driver
Radio driver for TR1001.
struct radio_driver tr1001_driver
Radio driver for TR1001.
Function Documentation
int tr1001_init (void)
Initialize the radio transceiver.
Turns on reception of bytes and installs the receive interrupt handler.
Definition at line 350 of file tr1001.c.
References CLOCK_SECOND, NULL, process_start(), PT_INIT, timer_set(), and tr1001_set_txpower().
void tr1001_set_txpower (unsigned char p)
Set the transmission power of the transceiver.
The sensor board is equipped with a DS1804 100 position trimmer potentiometer which is used to set the transmission input current to the radio transceiver chip, thus setting the transmission power of the radio transceiver.
This function sets the trimmer potentiometer to a value between 1 and 100.
Parameters:
p The power of the transceiver, between 1 (lowest) and 100 (highest).
Definition at line 320 of file tr1001.c.
Referenced by tr1001_init().