#define UTILS_DEBUG
#define SDDS_SELFTEST
#define PLATFORM_LINUX_SDDS_IFACE              "vioif0"
#define PLATFORM_LINUX_SDDS_IP_ADDRESS 			"fe80:2::5054:ff:fe12:3456"
#define PLATFORM_LINUX_SDDS_ADDRESS		PLATFORM_LINUX_SDDS_IP_ADDRESS
#define PLATFORM_LINUX_SDDS_PORT				23234

