#ifndef UTILS_DEBUG
#define UTILS_DEBUG
#endif
#ifndef SDDS_SELFTEST
#define SDDS_SELFTEST
#endif
#ifndef SDDS_HAS_QOS_RELIABILITY
#define SDDS_HAS_QOS_RELIABILITY
#endif
#ifndef SDDS_HAS_QOS_RELIABILITY_KIND_RELIABLE_BESTEFFORT
#define SDDS_HAS_QOS_RELIABILITY_KIND_RELIABLE_BESTEFFORT
#endif
