/*
* generated by Xtext
*/
package de.dopsy.contentassist;

import de.dopsy.contentassist.AbstractSDDSSystemProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SDDSSystemProposalProvider extends AbstractSDDSSystemProposalProvider {

}
