/*
* generated by Xtext
*/
package de.dopsy.outline;

import org.eclipse.xtext.ui.common.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class SDDSSystemTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
