#ifndef TWI_PCF_CONFIG_H_INCLUDED
#define TWI_PCF_CONFIG_H_INCLUDED

/* the pcf8591 access information */
#define DRIVER_TWI_PCF_8591P_ADDRESS 0x90
#define DRIVER_TWI_PCF_8591P_CONTROL 0
#define DRIVER_TWI_PCF_8591P_TAP 0

#endif
