APPLICATION_NAME = test_history_best_effort

export APPLICATION_NAME

all:
	$(MAKE) -f Makefile_2nd_lvl.mk $(APPLICATION_NAME) $(MAKEOPTS)

code:
	$(MAKE) -f Makefile_2nd_lvl.mk code

clean:
	$(MAKE) -f Makefile_2nd_lvl.mk clean
