/*
 * generated by Xtext
 */
package de.dopsy;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SDDSSystemUiModule extends de.dopsy.AbstractSDDSSystemUiModule {

}
