#ifndef PLATFORM_RUMP
#define PLATFORM_RUMP
#endif
#ifndef PLATFORM_LINUX_SDDS_IFACE
#define PLATFORM_LINUX_SDDS_IFACE "vioif0"
#endif
#ifndef PLATFORM_LINUX_SDDS_IP_ADDRESS
#define PLATFORM_LINUX_SDDS_IP_ADDRESS "fe80::5054:0ff:fe62:bf16"
#endif
#ifndef PLATFORM_LINUX_SDDS_PORT
#define PLATFORM_LINUX_SDDS_PORT 23234
#endif
#ifndef PLATFORM_LINUX_SDDS_ADDRESS
#define PLATFORM_LINUX_SDDS_ADDRESS PLATFORM_LINUX_SDDS_IP_ADDRESS"%"PLATFORM_LINUX_SDDS_IFACE
#endif
#ifndef FEATURE_SDDS_MULTICAST_ENABLED
#define FEATURE_SDDS_MULTICAST_ENABLED
#endif
#ifndef FEATURE_SDDS_BUILTIN_TOPICS_ENABLED
#define FEATURE_SDDS_BUILTIN_TOPICS_ENABLED
#endif
#ifndef FEATURE_SDDS_DISCOVERY_ENABLED
#define FEATURE_SDDS_DISCOVERY_ENABLED
#endif
#ifndef SDDS_NET_MAX_BUF_SIZE
#define SDDS_NET_MAX_BUF_SIZE 8192
#endif
#ifndef SDDS_NET_MAX_LOCATOR_COUNT
#define SDDS_NET_MAX_LOCATOR_COUNT 20
#endif
#ifndef SDDS_DISCOVERY_RECEIVE_TIMER
#define SDDS_DISCOVERY_RECEIVE_TIMER 1
#endif
#ifndef SDDS_DISCOVERY_PARTICIPANT_TIMER
#define SDDS_DISCOVERY_PARTICIPANT_TIMER 1
#endif
#ifndef SDDS_DISCOVERY_PUBLICATION_TIMER
#define SDDS_DISCOVERY_PUBLICATION_TIMER 5
#endif
#ifndef SDDS_DISCOVERY_TOPIC_TIMER
#define SDDS_DISCOVERY_TOPIC_TIMER 0
#endif
