APPLICATION_NAME = test_echo_linux_reliability_reliable_ack

export APPLICATION_NAME

all:
	$(MAKE) -f Makefile_2nd_lvl.mk $(APPLICATION_NAME) $(MAKEOPTS)

code:
	$(MAKE) -f Makefile_2nd_lvl.mk code

clean:
	$(MAKE) -f Makefile_2nd_lvl.mk clean
