/*
 * generated by Xtext
 */
package de.dopsy;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SDDS2RuntimeModule extends de.dopsy.AbstractSDDS2RuntimeModule {

}
